# Generated by Django 3.2.11 on 2025-03-11 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('cover', models.CharField(blank=True, max_length=200, null=True)),
                ('pid', models.BigIntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'b_category',
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('log_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'b_error_log',
            },
        ),
        migrations.CreateModel(
            name='OpLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('re_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('re_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('re_url', models.CharField(blank=True, max_length=200, null=True)),
                ('re_method', models.CharField(blank=True, max_length=10, null=True)),
                ('re_content', models.CharField(blank=True, max_length=200, null=True)),
                ('access_time', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'b_op_log',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('role', models.CharField(blank=True, max_length=2, null=True)),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '封号')], default='0', max_length=1)),
                ('nickname', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('admin_token', models.CharField(blank=True, max_length=32, null=True)),
                ('token', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'b_user',
            },
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('cover', models.ImageField(null=True, upload_to='cover/')),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('price', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('0', '上架'), ('1', '下架')], default='0', max_length=1)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('pv', models.IntegerField(default=0)),
                ('rate', models.IntegerField(default=3)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_thing', to='myapp.category')),
            ],
            options={
                'db_table': 'b_thing',
            },
        ),
    ]
