# Generated by Django 3.2.11 on 2025-03-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
