# Generated by Django 3.2.11 on 2025-03-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exp',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
