# Generated by Django 3.2.11 on 2025-03-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pid',
            field=models.BigIntegerField(default=-1),
        ),
    ]
