# Generated by Django 3.2.11 on 2025-03-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_category_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='cover',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='thing',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
