# Generated by Django 3.2.11 on 2025-03-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20250314_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='summary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
