# Generated by Django 3.2.11 on 2025-03-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_thing_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='seo_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='thing',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='thing',
            name='seo_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
