# Generated by Django 3.2.11 on 2025-03-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20250315_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='properties',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
