# Generated by Django 3.2.11 on 2025-03-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_thing_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='properties',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
