# Generated by Django 3.2.11 on 2025-03-15 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_thing_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_thing', to='myapp.category'),
        ),
    ]
