# Generated by Django 3.2.11 on 2025-03-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(blank=True, max_length=200, null=True)),
                ('reply', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('0', '上架'), ('1', '下架')], default='0', max_length=1)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('pv', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'b_faq',
            },
        ),
    ]
