# Generated by Django 3.2.11 on 2025-03-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_inquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.CharField(blank=True, max_length=1000, null=True)),
                ('raw', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('0', '上架'), ('1', '下架')], default='0', max_length=1)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('pv', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'b_download',
            },
        ),
    ]
