# Generated by Django 3.2.11 on 2025-03-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
