# Generated by Django 3.2.11 on 2025-03-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_download_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicSite',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=2, null=True)),
                ('site_name', models.CharField(blank=True, max_length=100, null=True)),
                ('site_nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('site_logo', models.CharField(blank=True, max_length=100, null=True)),
                ('site_ico', models.CharField(blank=True, max_length=100, null=True)),
                ('site_address', models.CharField(blank=True, max_length=100, null=True)),
                ('site_copyright', models.CharField(blank=True, max_length=100, null=True)),
                ('site_code', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'b_basic_site',
            },
        ),
    ]
