# Generated by Django 3.2.11 on 2025-03-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_basicsite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicsite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
