# Generated by Django 3.2.11 on 2025-03-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_basicsite_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicsite',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
