# Generated by Django 3.2.11 on 2025-03-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_basicsite_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicTdk',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tdk_home_title', models.CharField(blank=True, max_length=100, null=True)),
                ('tdk_home_keywords', models.CharField(blank=True, max_length=200, null=True)),
                ('tdk_home_description', models.CharField(blank=True, max_length=500, null=True)),
                ('tdk_product_title', models.CharField(blank=True, max_length=100, null=True)),
                ('tdk_product_keywords', models.CharField(blank=True, max_length=200, null=True)),
                ('tdk_product_description', models.CharField(blank=True, max_length=500, null=True)),
                ('tdk_about_title', models.CharField(blank=True, max_length=100, null=True)),
                ('tdk_about_keywords', models.CharField(blank=True, max_length=200, null=True)),
                ('tdk_about_description', models.CharField(blank=True, max_length=500, null=True)),
                ('tdk_contact_title', models.CharField(blank=True, max_length=100, null=True)),
                ('tdk_contact_keywords', models.CharField(blank=True, max_length=200, null=True)),
                ('tdk_contact_description', models.CharField(blank=True, max_length=500, null=True)),
                ('tdk_news_title', models.CharField(blank=True, max_length=100, null=True)),
                ('tdk_news_keywords', models.CharField(blank=True, max_length=200, null=True)),
                ('tdk_news_description', models.CharField(blank=True, max_length=500, null=True)),
                ('tdk_case_title', models.CharField(blank=True, max_length=100, null=True)),
                ('tdk_case_keywords', models.CharField(blank=True, max_length=200, null=True)),
                ('tdk_case_description', models.CharField(blank=True, max_length=500, null=True)),
                ('tdk_download_title', models.CharField(blank=True, max_length=100, null=True)),
                ('tdk_download_keywords', models.CharField(blank=True, max_length=200, null=True)),
                ('tdk_download_description', models.CharField(blank=True, max_length=500, null=True)),
                ('tdk_faq_title', models.CharField(blank=True, max_length=100, null=True)),
                ('tdk_faq_keywords', models.CharField(blank=True, max_length=200, null=True)),
                ('tdk_faq_description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'b_basic_tdk',
            },
        ),
    ]
