# Generated by Django 3.2.11 on 2025-03-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_basictdk'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicBanner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('banner_home', models.CharField(blank=True, max_length=300, null=True)),
                ('banner_product', models.CharField(blank=True, max_length=100, null=True)),
                ('banner_about', models.CharField(blank=True, max_length=100, null=True)),
                ('banner_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('banner_news', models.CharField(blank=True, max_length=100, null=True)),
                ('banner_case', models.CharField(blank=True, max_length=100, null=True)),
                ('banner_download', models.CharField(blank=True, max_length=100, null=True)),
                ('banner_faq', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'b_basic_banner',
            },
        ),
    ]
