# Generated by Django 3.2.11 on 2025-03-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_basicglobal'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicglobal',
            name='global_wechat_qrcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
