# Generated by Django 3.2.11 on 2025-03-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_basicglobal_global_wechat_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicAdditional',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('additional_mission', models.CharField(blank=True, max_length=500, null=True)),
                ('additional_task', models.CharField(blank=True, max_length=500, null=True)),
                ('global_addition_about_image', models.CharField(blank=True, max_length=100, null=True)),
                ('global_addition_company_image', models.CharField(blank=True, max_length=100, null=True)),
                ('param_one_name', models.CharField(blank=True, max_length=100, null=True)),
                ('param_one_value', models.CharField(blank=True, max_length=100, null=True)),
                ('param_two_name', models.CharField(blank=True, max_length=100, null=True)),
                ('param_two_value', models.CharField(blank=True, max_length=100, null=True)),
                ('param_three_name', models.CharField(blank=True, max_length=100, null=True)),
                ('param_three_value', models.CharField(blank=True, max_length=100, null=True)),
                ('param_four_name', models.CharField(blank=True, max_length=100, null=True)),
                ('param_four_value', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'b_basic_additional',
            },
        ),
    ]
