# Generated by Django 3.2.11 on 2025-03-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_basicadditional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment_name', models.CharField(blank=True, max_length=100, null=True)),
                ('comment_location', models.CharField(blank=True, max_length=100, null=True)),
                ('comment_content', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'b_comment',
            },
        ),
    ]
