# Generated by Django 3.2.11 on 2025-03-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
