# Generated by Django 3.2.11 on 2025-03-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_inquiry_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('about_introduction', models.CharField(blank=True, max_length=1000, null=True)),
                ('about_cover', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'b_about',
            },
        ),
    ]
