# Generated by Django 3.2.11 on 2025-03-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_about'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='oplog',
            index=models.Index(fields=['re_time'], name='re_time'),
        ),
    ]
