# Generated by Django 3.2.11 on 2025-03-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_auto_20250327_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicsite',
            name='site_switch_about',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='basicsite',
            name='site_switch_case',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='basicsite',
            name='site_switch_contact',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='basicsite',
            name='site_switch_download',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='basicsite',
            name='site_switch_faq',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='basicsite',
            name='site_switch_news',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='basicsite',
            name='site_switch_product',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
