# Generated by Django 3.2.11 on 2025-03-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_auto_20250327_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicsite',
            name='status',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
