# Generated by Django 3.2.11 on 2025-04-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_basicsite_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
