# Generated by Django 3.2.11 on 2025-04-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_case_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicadditional',
            name='additional_task',
        ),
        migrations.AddField(
            model_name='basicadditional',
            name='additional_about',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='basicadditional',
            name='global_addition_mission_image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='basicadditional',
            name='additional_mission',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
