# Generated by Django 3.2.11 on 2025-04-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_auto_20250419_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('advantage_image', models.CharField(blank=True, max_length=100, null=True)),
                ('advantage_title', models.CharField(blank=True, max_length=100, null=True)),
                ('advantage_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'b_advantage',
            },
        ),
    ]
