# Generated by Django 3.2.11 on 2025-04-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_advantage'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicadditional',
            name='global_addition_contact_image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
