# Generated by Django 3.2.11 on 2025-04-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_basicadditional_global_addition_contact_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_cover',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
