# Generated by Django 3.2.11 on 2025-04-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_comment_comment_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='dimension',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
