# Generated by Django 3.2.11 on 2025-04-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_thing_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicsite',
            name='site_gaid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
