# Generated by Django 3.2.11 on 2025-04-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_basicsite_site_gaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicadditional',
            name='global_addition_company_image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
