# Generated by Django 3.2.11 on 2025-04-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_alter_basicadditional_global_addition_company_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicadditional',
            name='ext01',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basicadditional',
            name='ext02',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basicadditional',
            name='ext03',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='basicadditional',
            name='ext04',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='basicadditional',
            name='ext05',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='basicadditional',
            name='ext06',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
