# Generated by Django 3.2.11 on 2025-06-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_auto_20250430_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thing',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
