# Generated by Django 3.2.11 on 2025-06-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_auto_20250606_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicadditional',
            name='ext02',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
