from myapp.views.admin.thing import *
from myapp.views.admin.category import *
from myapp.views.admin.user import *
from myapp.views.admin.news import *
from myapp.views.admin.about import *
from myapp.views.admin.comment import *
from myapp.views.admin.advantage import *
from myapp.views.admin.inquiry import *
from myapp.views.admin.basicSite import *
from myapp.views.admin.basicBanner import *
from myapp.views.admin.basicGlobal import *
from myapp.views.admin.basicAdditional import *
from myapp.views.admin.overview import *
from myapp.views.admin.opLog import *
from myapp.views.admin.errorLog import *
from myapp.views.admin.cdn import *
